services:
  narada:
    build: .
    container_name: narada
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services.json:/app/services.json:ro
      - /mnt/data/syncthing/data/sms:/imports/sms:ro
    networks:
      - mariadb_homelab
      - rabbitmq_default

networks:
  mariadb_homelab:
    external: true

  rabbitmq_default:
    external: true
