services:
  narada:
    build: .
    container_name: narada
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services.json:/app/services.json:ro
    networks:
      default:
        external: true
        name: <dockge-shared-network-name>