CREATE TABLE merchant_aliases (
    from_key VARCHAR(255) NOT NULL PRIMARY KEY,
    to_key VARCHAR(255) NOT NULL,
    label VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
